"""A plan's folder in the record format (hal2's decision record `record-formats`): the files `plan.py new` writes
beside plan.md, a plan's header values in either form, and the plan-folder check (`plan.py check`).

A plan.md with front matter (`type: Plan`) is a record: its landing, grilled, finished and autogenerated values are
front matter keys, its decisions and questions are the two ledgers and its state the committed handoff.md. A plan.md
without front matter is legacy: `<Key>: <value>` lines below the title, checked by nothing.
"""

import datetime as dt
import re
import subprocess
from pathlib import Path

import envelope
import records
import rules

TEMPLATES = Path(__file__).resolve().parent.parent / "templates"
SIBLINGS = ("decisions.md", "questions.md", "handoff.md")
FILES = ("plan.md", *SIBLINGS)
DESCRIPTION = 200


def is_record(text: str) -> bool:
    """Has the file front matter with a `type`? Broken front matter counts: the check names what is wrong."""
    try:
        return bool(envelope.get(text, "type"))
    except envelope.FormatError:
        return text.startswith("---\n")


def header(text: str, key: str) -> str:
    """A record plan's value of the legacy header `key` (`Landing` is the key `landing`)."""
    try:
        value = envelope.get(text, key.lower())
    except envelope.FormatError:
        return ""
    return "" if value is None else str(value)


def raw(value: str) -> str:
    """`value` as front matter: plain when the subset reads it back unchanged, else quoted."""
    try:
        plain = envelope.scalar(envelope.strip_comment(value)) == value
    except envelope.FormatError:
        plain = False
    return value if plain and value else envelope.quote(value)


def write_key(path: Path, key: str, value: str | None) -> None:
    """Set one front matter line; a file that already says so is not written (hal2's autoclear takes a handoff.md
    written just now for a hand-off)."""
    text = path.read_text()
    new = envelope.set_key(text, key, value)
    if new != text:
        path.write_text(new)


def set_header(path: Path, key: str, value: str | None) -> None:
    write_key(path, key.lower(), None if value is None else raw(value))


def sync_status(path: Path, finished: bool) -> None:
    """A record plan is `done` exactly when no step is open, and its ledgers and handoff are `closed` with it
    (an `abandoned` plan stays abandoned)."""
    if envelope.get(path.read_text(), "status") == "abandoned":
        return
    write_key(path, "status", "done" if finished else "open")
    for name in SIBLINGS:
        other = path.parent / name
        if other.is_file() and is_record(other.read_text()):
            write_key(other, "status", "closed" if finished else "open")


def describe(goal: str, title: str) -> str:
    """The plan's `description`: the goal's first sentence, at most 200 characters; the title without a goal."""
    text = " ".join((goal or title).split())
    first = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0]
    if len(first) <= DESCRIPTION:
        return first
    return first[:DESCRIPTION - 1].rsplit(" ", 1)[0].rstrip(",;:") + "…"


def git(root: Path, *args: str) -> str:
    out = subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True)
    return out.stdout.strip() if out.returncode == 0 else ""


def fields(root: Path, number: int, title: str, goal: str, landing: str) -> dict:
    """What the templates of a new plan folder are filled with."""
    return {"number": f"{number:04d}", "id": number, "title": title, "quoted_title": envelope.quote(title),
            "description": envelope.quote(describe(goal, title)), "goal": goal or "<one or two sentences>",
            "date": dt.date.today().isoformat(), "landing": landing,
            "branch": raw(git(root, "branch", "--show-current") or "none"),
            "at": envelope.quote(git(root, "rev-parse", "--short", "HEAD") or "none")}


def scaffold(plan: Path, values: dict) -> list[Path]:
    """Write the ledgers and the handoff a record plan lacks; never overwrites one."""
    written = []
    for name in SIBLINGS:
        path = plan.parent / name
        if not path.exists():
            path.write_text((TEMPLATES / name).read_text().format(**values))
            written.append(path)
    return written


def scaffold_existing(root: Path, plan: Path) -> list[Path]:
    """The same for a plan that exists: a legacy plan gets none (it is migrated as a whole or not at all)."""
    text = plan.read_text()
    if not is_record(text):
        return []
    return scaffold(plan, fields(root, int(plan.parent.name[:4]), str(envelope.get(text, "title") or ""), "",
                                 str(envelope.get(text, "landing") or "manual")))


def check_folder(folder: Path, base: Path) -> tuple[int, list[str]]:
    """The records of one plan folder and their problems, each line starting with the file's path."""
    tree = records.Tree(folder.parent.parent.resolve(), base.resolve())
    found = {name: tree.record(f"plans/{folder.name}/{name}") for name in FILES if (folder / name).is_file()}
    typed = {name: rec for name, rec in found.items() if rec and (rec.type or rec.error)}
    problems = [f"{folder / name}: {p}" for name, rec in typed.items() for p in records.check(rec, tree, rules.BY_TYPE)]
    if "plan.md" in typed:
        problems += [f"{folder / name}: missing or without front matter, beside a plan in the record format "
                     "(`plan.py scaffold` writes a missing one)" for name in SIBLINGS if name not in typed]
    return len(typed), problems


def check(folders: list[Path], base: Path) -> tuple[int, list[str]]:
    count, problems = 0, []
    for folder in folders:
        n, found = check_folder(folder, base)
        count, problems = count + n, problems + found
    return count, problems
