#!/usr/bin/env python3
"""Deterministic bookkeeping for plans under plans/ at the repository root.

A plan is a folder plans/<NNNN>-<slug>/ holding plan.md and the plan's helper files; plan.md has a markdown table whose header has the columns `#`, `Step` and `Status`
(optionally `Done when`). plans/CURRENT_PLAN holds the slug of the active plan (the Claude statusline shows it).
A flat plans/<NNNN>-<slug>.md from before the folder layout is still read and updated.

`new` writes the plan folder in the record format (folder.py; hal2's decision record `record-formats`): plan.md with
a front matter envelope, the ledgers decisions.md and questions.md and the committed handoff.md. A plan.md without
front matter is legacy: its `Landing:`, `Grilled:`, `Finished:` and `Autogenerated:` values are lines below the title
(a record's: the front matter keys `landing`, `grilled`, `finished`, `autogenerated`; the JSON is the same for both,
`format` says which).

  plan.py new "<title>" [--goal "<goal>"] [--research] [--no-current] [--fetch]
                                                           create the next plan from the template; its number
                                                           is unique across all worktrees and branches
                                                           (plan_number.py; --fetch sees other clones too);
                                                           --research: a research plan, slug <NNNN>-research-<topic>;
                                                           writes `landing: auto` (--manual-landing, and every
                                                           research plan: manual);
                                                           --autogenerated <by>: `autogenerated: <by>, <date>`
                                                           (a plan a watcher made; hal2 marks it)
  plan.py current                                          print the current plan as JSON
  plan.py list                                             print every plan as JSON
  plan.py use <slug-or-number>                             make a plan current
  plan.py status <step> "<status>" [--plan <slug>]         set one step's Status cell; `next` also writes the
                                                           step's file steps/<step>.md from templates/step.md
                                                           when it is missing (never overwrites; not for a
                                                           parallel plan, whose brief is `brief`), named in the
                                                           JSON's `step_file`
  plan.py grilled [--auto] [--plan <slug>]                 set the plan's `Grilled:` line to today; --auto counts
                                                           one autogrill round: `Grilled: <date> (autogrill ×n)`,
                                                           a grill by the user adds `, grill`
  plan.py landing auto|manual [--plan <slug>]              set the plan's `Landing:` line: auto lands the plan
                                                           with /mtm when its last step is done, manual waits
                                                           for the user's /mtm (a plan without the line)
  plan.py uat [--plan <slug>] [--shotfile <name>]          scaffold the plan's uat.md (checks the user runs on the
                                                           default branch after the landing) from the template;
                                                           the shotfile defaults to the title's first word
  plan.py check [<plan folder>...]                         the plan-folder check: exit 1 when a plan number is
                                                           used twice or hal2's records checker (`hal2-cli-records
                                                           check --json`, checker.py: $HAL2_CLI_RECORDS, else on
                                                           PATH) finds a problem in a plan folder's records
                                                           (plan.md, decisions.md, questions.md, handoff.md); one
                                                           problem per line; legacy plans pass; named folders: only
                                                           those (an example folder laid out like a repository:
                                                           `--folder` of the tree holding its plans/); without the
                                                           checker one line `records unchecked: ...`, exit 0
  plan.py scaffold [--plan <slug>]                         write the ledgers and the handoff a plan in the record
                                                           format lacks (never overwrites one)
  plan.py -g ...                                           the same on the global plans folder (hal2's
                                                           plans.toml root, default ~/Documents/hal2/plans;
                                                           --global-root <dir> overrides): new (through
                                                           `hal2-cli-plans new --global`), list, status,
                                                           grilled with --plan <n>; no CURRENT_PLAN there

A parallel plan (`new --parallel`; its step table has the columns `| # | Step | Needs | Touches | Who | Done when |
Status |`, parallel.py) adds `parallel`, `running` and `ready` to the JSON, and these commands (skills plan 0013):
  plan.py ready [--limit <n>] [--json]                     the steps that can start now: open, every Need done,
                                                           their Touches free (greedy in table order); --json adds
                                                           why each other open step waits
  plan.py assign <step> <who> [--force]                    who: lead, subagent, user or slot NN (30-99); sets Who
                                                           and `running` (a step not ready only with --force); a
                                                           slot NN that exists gets its plans/LEAD marker; a slot
                                                           another step holds, whose marker names other work or
                                                           that runs a farmer servant only with --force
  plan.py brief <step>                                     scaffold steps/<step>.md (templates/step-brief.md) and
                                                           print the subservant's exact first prompt
  plan.py report <step>                                    scaffold reports/<step>.md (templates/report.md)
  plan.py reports [--no-fetch]                             the running subservants' reports arrived on origin/NN
  plan.py watch [--interval 60] [--rounds n]               one line per newly arrived report (the lead's Monitor)
A cell holds a literal `|` written `\\|`. In a subservant's slot (plans/LEAD: `<lead-slot> <plan> <step>`, `lead` in
the JSON) new, status, assign, grilled, landing, uat and brief are refused: plan.md is the lead's (also with
--root <lead's checkout> when the current directory is in a marked slot).

Run from anywhere inside the repo, or pass --root. Prints JSON on stdout; exits 1 with a message on stderr.

The JSON's `landing` is the plan's `Landing:` line (auto|manual; none for a global plan), each step's
`after_landing` says its done-when starts with "after the landing" (or the older "after the user's `/mtm`"), `next`
is the first open step to run before the landing (an after-landing step only when no other is open), `land` is
`ready` when no open step must run before the landing (`wait` otherwise; `manual`, `none` from `landing`), and
`problems` lists after-landing steps followed by steps that are not. `current` and `status` add `switch`: the
`next` step's model and effort when they differ from the running Claude Code session's (session.py), else null.
"""
import argparse
import datetime as dt
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

import checker
import envelope
import folder
import parallel
import plan_number
import session

PLANS = Path("plans")
POINTER = "CURRENT_PLAN"
PLAN_RE = re.compile(r"^(\d{4})-[a-z0-9-]+$")
MAIN = "plan.md"
TEMPLATE = Path(__file__).resolve().parent.parent / "templates" / "plan.md"
UAT_TEMPLATE = TEMPLATE.parent / "uat.md"
STEP_TEMPLATE = TEMPLATE.parent / "step.md"
STEPS = "steps"
UAT = "uat.md"
UAT_CHECK = re.compile(r"^## (U\d+)\b")
RESEARCH = "research"
LANDINGS = ("auto", "manual")
AFTER_LANDING = ("after the landing", "after the user's `/mtm`", "after the user's /mtm")
GLOBAL = False


class PlanError(Exception):
    pass


def use_global(folder: Path) -> Path:
    """Work on the global plans folder `folder`: plans are `folder/<slug>/plan.md`; the root to pass on."""
    global PLANS, GLOBAL
    PLANS = Path(folder.name)
    GLOBAL = True
    return folder.parent


def global_folder() -> Path:
    """hal2's global plans folder (`hal2-cli-plans settings --json`)."""
    if shutil.which("hal2-cli-plans") is None:
        raise PlanError("hal2-cli-plans is missing: install hal2 (cargo install --path apps/hal2-cli-plans)")
    out = subprocess.run(["hal2-cli-plans", "settings", "--json"], capture_output=True, text=True)
    if out.returncode != 0:
        raise PlanError(f"hal2-cli-plans settings: {out.stderr.strip()}")
    return Path(json.loads(out.stdout)["root"])


def new_global_plan(folder: Path, title: str, goal: str, research: bool) -> Path:
    """A global plan, numbered and written by hal2 (`hal2-cli-plans new --global`)."""
    if shutil.which("hal2-cli-plans") is None:
        raise PlanError("hal2-cli-plans is missing: install hal2 (cargo install --path apps/hal2-cli-plans)")
    args = ["hal2-cli-plans", "new", title, "--global", "--json"]
    if goal:
        args += ["--goal", goal]
    if research:
        args.append("--research")
    out = subprocess.run(args, capture_output=True, text=True)
    if out.returncode != 0:
        raise PlanError(f"hal2-cli-plans new: {out.stderr.strip()}")
    path = Path(json.loads(out.stdout)["path"]).resolve()
    if path.parent.parent.resolve() != folder.resolve():
        raise PlanError(f"hal2-cli-plans created {path}, outside the global folder {folder}")
    return path


def find_root(start: Path) -> Path:
    for folder in [start, *start.parents]:
        if (folder / ".git").exists():
            return folder
    raise PlanError(f"not inside a git repository: {start}")


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    if not slug:
        raise PlanError("title needs at least one letter or digit")
    return slug[:60].rstrip("-")


def research_slug(slug: str) -> str:
    """`research-<slug>` for a research plan, unless the slug already starts with it."""
    if slug == RESEARCH or slug.startswith(RESEARCH + "-"):
        return slug
    return f"{RESEARCH}-{slug}"[:60].rstrip("-")


def is_research(slug: str) -> bool:
    """A research plan: `<NNNN>-research-<topic>`."""
    name = slug[5:]
    return name == RESEARCH or name.startswith(RESEARCH + "-")


def slug_of(path: Path) -> str:
    """`0002-foo` for plans/0002-foo/plan.md (and for a flat plans/0002-foo.md)."""
    return path.parent.name if path.name == MAIN else path.stem


def plan_files(root: Path) -> list[Path]:
    """Every plan's markdown file: plans/<slug>/plan.md, or a flat plans/<slug>.md."""
    folder = root / PLANS
    if not folder.is_dir():
        return []
    found = [p / MAIN for p in folder.iterdir() if p.is_dir() and PLAN_RE.match(p.name) and (p / MAIN).is_file()]
    found += [p for p in folder.iterdir() if p.is_file() and p.suffix == ".md" and PLAN_RE.match(p.stem)]
    return sorted(found, key=slug_of)


def resolve(root: Path, ref: str) -> Path:
    """A plan by slug (`0002-foo`), file name, or bare number (`2`, `0002`)."""
    ref = ref.strip().removesuffix(".md").removesuffix("/" + MAIN).rstrip("/")
    for path in plan_files(root):
        slug = slug_of(path)
        if slug == ref or (ref.isdigit() and int(ref) == int(slug[:4])):
            return path
    raise PlanError(f"no plan matches '{ref}' in {PLANS}")


def current_path(root: Path) -> Path:
    pointer = root / PLANS / POINTER
    if not pointer.is_file() or not pointer.read_text().strip():
        raise PlanError(f"no current plan: {PLANS / POINTER} is missing or empty")
    ref = pointer.read_text().strip()
    try:
        return resolve(root, ref)
    except PlanError:
        # A shot (`<shotfile>/<n>`) or a task name: current work, but no plan.
        raise PlanError(f"no current plan: {PLANS / POINTER} names '{ref}', which is not a plan") from None


def set_current(root: Path, path: Path) -> None:
    (root / PLANS / POINTER).write_text(slug_of(path) + "\n")


def split_row(line: str) -> list[str]:
    """A table row's cells; `\\|` inside a cell is a literal `|`, not a column border."""
    cells = re.split(r"(?<!\\)\|", line.strip())
    if cells and not cells[0].strip():
        cells = cells[1:]
    if cells and not cells[-1].strip():
        cells = cells[:-1]
    return [cell.strip().replace("\\|", "|") for cell in cells]


def join_row(cells: list[str]) -> str:
    return "| " + " | ".join(cell.replace("|", "\\|") for cell in cells) + " |"


def steps_table(lines: list[str]) -> tuple[int, dict[str, int]]:
    """Index of the step table's header line and its column positions."""
    for i, line in enumerate(lines):
        if line.lstrip().startswith("|"):
            cells = [c.lower() for c in split_row(line)]
            if "#" in cells and "step" in cells and "status" in cells:
                return i, {name: cells.index(name) for name in cells}
    raise PlanError("no step table with columns '#', 'Step' and 'Status'")


def run_default(text: str) -> tuple[str, str]:
    """The plan's default model and effort: a record's `run` key, a legacy plan's `Run: <model> <effort>` line
    (`-` for none); empty strings without it."""
    words = [w.strip("`") for w in header_value(text, "Run").split()] + ["", ""]
    return tuple("" if w == "-" else w for w in words[:2])


def read_steps(text: str) -> list[dict]:
    lines = text.splitlines()
    run_model, run_effort = run_default(text)
    try:
        header, cols = steps_table(lines)
    except PlanError:
        return []
    steps, width = [], max(cols.values()) + 1
    for row, line in enumerate(lines[header + 2:], 1):
        if not line.lstrip().startswith("|"):
            break
        cells = split_row(line)
        if len(cells) < width:
            raise PlanError(f"row {row} of the step table has {len(cells)} cells, its header {width}: write a `|` "
                            "inside a cell as `\\|`")
        step = {
            "number": cells[cols["#"]],
            "step": cells[cols["step"]],
            "done_when": cells[cols["done when"]] if "done when" in cols else "",
            "status": cells[cols["status"]],
            "model": (cells[cols["model"]] if "model" in cols else "") or run_model,
            "effort": (cells[cols["effort"]] if "effort" in cols else "") or run_effort,
        }
        if parallel.is_parallel(cols):
            parallel.enrich(step, cells, cols)
        steps.append(step)
    for step in steps:
        step["after_landing"] = step["done_when"].lower().lstrip("*_ ").startswith(AFTER_LANDING)
    return steps


def header_value(text: str, key: str) -> str:
    """The value of a `<key>: <value>` line above the plan's first section; of a plan in the record format, its
    front matter key."""
    if folder.is_record(text):
        return folder.header(text, key)
    for line in text.splitlines():
        if line.startswith("## "):
            break
        if line.startswith(key + ":"):
            return line.split(":", 1)[1].strip()
    return ""


def landing_of(text: str) -> str:
    """auto, manual (also for a plan without the line or with an unknown value) or none (a global plan)."""
    if GLOBAL:
        return "none"
    value = header_value(text, "Landing").lower()
    return value if value in LANDINGS else "manual"


def problems_of(steps: list[dict]) -> list[str]:
    """After-landing steps that other steps follow: they belong at the end of the table."""
    problems = []
    for i, step in enumerate(steps):
        later = [s["number"] for s in steps[i + 1:] if not s["after_landing"]]
        if step["after_landing"] and later:
            problems.append(f"step {step['number']} is checked after the landing but step(s) {', '.join(later)} "
                            "follow it: move it to the end, a plan lands once, after all its other steps")
    return problems


def describe(root: Path, path: Path) -> dict:
    text = path.read_text()
    steps = read_steps(text)
    title = next((l[2:].strip() for l in text.splitlines() if l.startswith("# ")), slug_of(path))
    grilled = header_value(text, "Grilled")
    open_steps = [s for s in steps if not s["status"].lower().startswith("done")]
    before_landing = [s for s in open_steps if not s["after_landing"]]
    landing = landing_of(text)
    land = landing if landing != "auto" else ("wait" if before_landing else "ready")
    pointer = root / PLANS / POINTER
    extra = {}
    if steps and "needs" in steps[0]:
        ready, _ = parallel.schedule(steps, parallel.capacity(text))
        extra = {"parallel": True, "running": [s for s in steps if parallel.kind(s["status"]) == "running"],
                 "ready": ready}
    if not GLOBAL and (marker := parallel.read_marker(root)):
        extra["lead"] = marker
    return {
        "slug": slug_of(path),
        "path": str(path.relative_to(root)),
        "title": title,
        "research": is_research(slug_of(path)),
        "current": pointer.is_file() and pointer.read_text().strip() == slug_of(path),
        "grilled": grilled,
        "finished": header_value(text, "Finished"),
        "uat": str((path.parent / UAT).relative_to(root)) if (path.parent / UAT).exists() and path.name == MAIN else "",
        "uat_checks": uat_checks(path),
        "autogrill_rounds": grill_rounds(grilled)[0],
        "autogenerated": header_value(text, "Autogenerated"),
        "format": "record" if folder.is_record(text) else "legacy",
        **{name[:-3]: str((path.parent / name).relative_to(root)) if path.name == MAIN and (path.parent / name).is_file()
           else "" for name in folder.SIBLINGS},
        "done": len(steps) - len(open_steps),
        "total": len(steps),
        "next": (before_landing or open_steps or [None])[0],
        "landing": landing,
        "land": land,
        "problems": problems_of(steps) + (parallel.problems(steps) if extra.get("parallel") else []),
        "steps": steps,
        **extra,
    }


def describe_safe(root: Path, path: Path) -> dict:
    """describe(), or the plan's error as its only problem: one broken table never hides the other plans."""
    try:
        return describe(root, path)
    except PlanError as error:
        return {"slug": slug_of(path), "path": str(path.relative_to(root)), "problems": [str(error)], "steps": []}


def parallel_table(text: str) -> str:
    """The template's step table with the parallel plan's columns Needs, Touches and Who (the UAT step needs every
    step before it)."""
    lines, out, ids, header = text.split("\n"), [], [], None
    for line in lines:
        if not line.lstrip().startswith("|"):
            out.append(line)
            continue
        cells = split_row(line)
        if header is None:
            header = cells
            cells[2:2] = ["Needs", "Touches", "Who"]
        elif set("".join(cells)) <= set("-: "):
            cells[2:2] = ["---"] * 3
        else:
            uat = "Write the UATs" in cells[1]
            cells[2:2] = [", ".join(ids) if uat else "", "docs" if uat else "", "lead" if uat else ""]
            ids.append(cells[0])
        out.append(join_row(cells))
    return "\n".join(out)


def new_plan(root: Path, title: str, goal: str, make_current: bool, fetch: bool = False,
             research: bool = False, landing: str = "auto", autogenerated: str = "", parallel_plan: bool = False) -> Path:
    slug = research_slug(slugify(title)) if research else slugify(title)
    if fetch:
        plan_number.git(root, "fetch", "--all", "--quiet")
    try:
        number = plan_number.next_number(root, slug)
    except plan_number.NumberError as error:
        raise PlanError(str(error)) from error
    path = root / PLANS / f"{number:04d}-{slug}" / MAIN
    path.parent.mkdir(parents=True, exist_ok=True)
    values = folder.fields(root, number, title, goal, landing)
    text = TEMPLATE.read_text().format(**values)
    if research:
        text = "\n".join(l for l in text.split("\n") if "Write the UATs" not in l)
    if parallel_plan:
        text = parallel_table(text)
    path.write_text(text)
    folder.scaffold(path, values)
    if autogenerated:
        set_header(path, "Autogenerated", f"{autogenerated}, {dt.date.today().isoformat()}")
    if make_current:
        set_current(root, path)
    return path


def set_status(path: Path, step: str, status: str) -> None:
    set_cells(path, step, {"status": status})


def scaffold_step(path: Path, step: str) -> Path | None:
    """Write `steps/<step>.md` from templates/step.md when the step becomes next (hal2's record
    plans-short-and-concise): never over an existing file, never for a flat plan (no folder) or a parallel plan
    (its brief is `plan.py brief`). The written file, or None."""
    target = path.parent / STEPS / f"{step}.md"
    if path.name != MAIN or target.exists():
        return None
    text = path.read_text()
    if parallel.is_parallel(steps_table(text.splitlines())[1]):
        return None
    row = next((s for s in read_steps(text) if s["number"] == step), None)
    if row is None:
        return None
    target.parent.mkdir(exist_ok=True)
    target.write_text(STEP_TEMPLATE.read_text().format(
        number=step, title=row["step"] or f"step {step}",
        task="<what to change: the files and packages, the approach, what the step must not touch>",
        done_when=row["done_when"] or "the step table's check"))
    return target


def set_cells(path: Path, step: str, values: dict[str, str]) -> None:
    """Set cells of one step's row by column name (lower case), keeping every other cell."""
    lines = path.read_text().splitlines(keepends=True)
    header, cols = steps_table([l.rstrip("\n") for l in lines])
    missing = [name for name in values if name not in cols]
    if missing:
        raise PlanError(f"the step table of {slug_of(path)} has no column {', '.join(missing)}")
    for i in range(header + 2, len(lines)):
        if not lines[i].lstrip().startswith("|"):
            break
        cells = split_row(lines[i])
        if cells and cells[cols["#"]] == step:
            for name, value in values.items():
                cells[cols[name]] = value
            lines[i] = join_row(cells) + "\n"
            path.write_text("".join(lines))
            stamp_finished(path)
            return
    raise PlanError(f"no step '{step}' in {slug_of(path)}")


def feature_of(title: str) -> str:
    """The feature a plan's title names first (`plugin-plan 9, 8` → `plugin-plan`): its shotfile's name."""
    return slugify(title.split()[0]) if title.split() else ""


def uat_checks(path: Path) -> list[str]:
    uat = path.parent / UAT
    if path.name != MAIN or not uat.exists():
        return []
    return [m.group(1) for l in uat.read_text().splitlines() if (m := UAT_CHECK.match(l))]


def write_uat(path: Path, shotfile: str = "") -> Path:
    """Scaffold the plan's `uat.md` from the template, typed (`type: UAT`, hal2's spec `uat`; never overwrites one)."""
    if path.name != MAIN:
        raise PlanError("a flat plan file has no folder for its uat.md: move it into plans/<NNNN>-<slug>/")
    uat = path.parent / UAT
    if not uat.exists():
        text = path.read_text()
        title = next((l.split(":", 1)[1].strip() for l in text.splitlines() if l.startswith("# Plan ")), slug_of(path))
        title = " ".join(title.split())
        number = slug_of(path)[:4]
        feature = shotfile.removesuffix(".md") or feature_of(title)
        out = UAT_TEMPLATE.read_text().format(
            number=number, id=int(number), title=title, quoted_title=envelope.quote(title),
            description=envelope.quote(f"The checks a person runs by hand on the default branch after plan {number} landed."),
            date=dt.date.today().isoformat(), shotfile=feature,
        )
        uat.write_text(out if feature else out.replace("shotfile: \n", ""))
    return uat


def stamp_finished(path: Path) -> None:
    """`Finished: <date>` once every step is done (hal2 shows it); gone again when a step reopens."""
    text = path.read_text()
    steps = read_steps(text)
    finished = bool(steps) and all(s["status"].lower().startswith("done") for s in steps)
    if finished and not header_value(text, "Finished"):
        set_header(path, "Finished", dt.date.today().isoformat())
    elif not finished and header_value(text, "Finished"):
        remove_header(path, "Finished")
    if folder.is_record(text):
        folder.sync_status(path, finished)


def remove_header(path: Path, key: str) -> None:
    if folder.is_record(path.read_text()):
        return folder.set_header(path, key, None)
    lines = path.read_text().splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("## "):
            return
        if line.startswith(key + ":"):
            del lines[i]
            if i < len(lines) and i > 0 and not lines[i].strip() and not lines[i - 1].strip():
                del lines[i]
            path.write_text("".join(lines))
            return


def set_header(path: Path, key: str, value: str) -> None:
    """Set the plan's `<key>: <value>` line, inserting it below the title when missing; a plan in the record format
    gets the front matter key."""
    if folder.is_record(path.read_text()):
        return folder.set_header(path, key, value)
    lines = path.read_text().splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("## "):
            break
        if line.startswith(key + ":"):
            lines[i] = f"{key}: {value}\n"
            path.write_text("".join(lines))
            return
    title = next((i for i, l in enumerate(lines) if l.startswith("# ")), -1)
    lines.insert(title + 1, f"\n{key}: {value}\n")
    path.write_text("".join(lines))


GRILL_NOTE = re.compile(r"\((?:autogrill [×x](\d+))?(?:, )?(grill)?\)")


def grill_rounds(grilled: str) -> tuple[int, bool]:
    """Autogrill rounds and whether the user grilled it, from `Grilled: <date> (autogrill ×2, grill)`; a plain
    date is a grill by the user."""
    if not grilled:
        return 0, False
    note = GRILL_NOTE.search(grilled)
    if not note:
        return 0, True
    return int(note.group(1) or 0), bool(note.group(2))


def set_grilled(path: Path, auto: bool = False) -> None:
    """Stamp today, counting autogrill rounds (`--auto`) next to a grill by the user."""
    rounds, manual = grill_rounds(header_value(path.read_text(), "Grilled"))
    if auto:
        rounds += 1
    else:
        manual = True
    notes = ([f"autogrill ×{rounds}"] if rounds else []) + (["grill"] if manual and rounds else [])
    today = dt.date.today().isoformat()
    set_header(path, "Grilled", f"{today} ({', '.join(notes)})" if notes else today)


def set_landing(path: Path, landing: str) -> None:
    if GLOBAL:
        raise PlanError("a global plan never lands: it belongs to no repository")
    set_header(path, "Landing", landing)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, help="repository root (default: found from the current directory)")
    parser.add_argument("-g", "--global", dest="is_global", action="store_true",
                        help="the global plans folder instead of a repository")
    parser.add_argument("--global-root", type=Path, help="the global plans folder (default: hal2's plans.toml)")
    sub = parser.add_subparsers(dest="command", required=True)
    p_new = sub.add_parser("new")
    p_new.add_argument("title")
    p_new.add_argument("--goal", default="")
    p_new.add_argument("--research", action="store_true")
    p_new.add_argument("--no-current", action="store_true")
    p_new.add_argument("--fetch", action="store_true")
    p_new.add_argument("--manual-landing", action="store_true",
                       help="write `Landing: manual`: the plan waits for the user's /mtm at its end")
    p_new.add_argument("--autogenerated", default="", metavar="BY",
                       help="write `Autogenerated: <BY>, <date>`: a plan a watcher (e.g. sanity-watch) made")
    sub.add_parser("current")
    sub.add_parser("list")
    p_use = sub.add_parser("use")
    p_use.add_argument("plan")
    p_status = sub.add_parser("status")
    p_status.add_argument("step")
    p_status.add_argument("status")
    p_status.add_argument("--plan")
    p_uat = sub.add_parser("uat")
    p_uat.add_argument("--plan")
    p_uat.add_argument("--shotfile", default="", help="the feature shotfile a failed check becomes a shot in")
    p_grilled = sub.add_parser("grilled")
    p_grilled.add_argument("--plan")
    p_grilled.add_argument("--auto", action="store_true",
                           help="one autogrill round: count it (`Grilled: <date> (autogrill ×n)`)")
    p_landing = sub.add_parser("landing")
    p_landing.add_argument("landing", choices=LANDINGS)
    p_landing.add_argument("--plan")
    p_check = sub.add_parser("check")
    p_check.add_argument("folders", nargs="*", type=Path,
                         help="plan folders to check (default: every plan's, and the plan numbers)")
    p_scaffold = sub.add_parser("scaffold")
    p_scaffold.add_argument("--plan")
    p_ready = sub.add_parser("ready", help="a parallel plan's steps that can start now")
    p_ready.add_argument("--plan")
    p_ready.add_argument("--limit", type=int)
    p_ready.add_argument("--json", action="store_true")
    p_assign = sub.add_parser("assign", help="give a ready step to lead, subagent, user or slot NN (30-99)")
    p_assign.add_argument("step")
    p_assign.add_argument("who", nargs="+")
    p_assign.add_argument("--plan")
    p_assign.add_argument("--force", action="store_true",
                          help="assign a step that is not ready, or to a slot that is taken")
    for name in ("brief", "report"):
        p = sub.add_parser(name)
        p.add_argument("step")
        p.add_argument("--plan")
    p_reports = sub.add_parser("reports", help="reports arrived on origin/NN of the running subservants")
    p_reports.add_argument("--plan")
    p_reports.add_argument("--no-fetch", action="store_true")
    p_watch = sub.add_parser("watch", help="print one line per newly arrived report (the lead's Monitor)")
    p_watch.add_argument("--plan")
    p_watch.add_argument("--interval", type=float, default=60)
    p_watch.add_argument("--rounds", type=int, default=0, help="stop after this many rounds (0: never)")
    p_new.add_argument("--parallel", action="store_true",
                       help="the step table gets the columns Needs, Touches and Who (a parallel plan)")
    args = parser.parse_args(argv)

    try:
        if args.is_global or args.global_root:
            return run_global(args)
        root = args.root.resolve() if args.root else find_root(Path.cwd())
        refuse_subservant(root, args.command)
        if args.command == "check":
            return run_check(root, args.folders)
        if args.command == "new":
            result = describe(root, new_plan(root, args.title, args.goal, not args.no_current, args.fetch,
                                             args.research,
                                             "manual" if args.manual_landing or args.research else "auto",
                                             args.autogenerated, args.parallel))
        elif args.command == "current":
            result = describe(root, current_path(root))
        elif args.command == "list":
            result = [describe_safe(root, p) for p in plan_files(root)]
        elif args.command == "use":
            path = resolve(root, args.plan)
            set_current(root, path)
            result = describe(root, path)
        elif args.command in PARALLEL_COMMANDS:
            path = resolve(root, args.plan) if args.plan else current_path(root)
            return run_parallel(root, path, args)
        else:
            path = resolve(root, args.plan) if args.plan else current_path(root)
            written = None
            if args.command == "status":
                set_status(path, args.step, args.status)
                if args.status.strip().lower() == "next":
                    written = scaffold_step(path, args.step)
            elif args.command == "landing":
                set_landing(path, args.landing)
            elif args.command == "uat":
                write_uat(path, args.shotfile)
            elif args.command == "scaffold":
                folder.scaffold_existing(root, path)
            else:
                set_grilled(path, args.auto)
            result = describe(root, path)
            if written:
                result["step_file"] = str(written.relative_to(root))
        if args.command in ("current", "status"):
            result["switch"] = session.switch_for(result["next"], session.current(
                os.getppid(), Path.home() / ".claude" / "settings.json"))
    except (PlanError, parallel.ParallelError) as error:
        print(f"plan.py: {error}", file=sys.stderr)
        return 1
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


def run_check(root: Path, folders: list[Path]) -> int:
    """The plan-folder check: the plan numbers, then hal2's records checker (checker.py) over the plan folders, or
    over the named ones only. A plan.md without front matter is legacy and passes; without the checker the records
    are unchecked (one line, no failure)."""
    code = 0
    if folders:
        missing = [str(f) for f in folders if not (f / MAIN).is_file()]
        if missing:
            raise PlanError(f"no plan folder (a folder holding {MAIN}): {', '.join(missing)}")
    else:
        code = plan_number.main(["--root", str(root), "check"])
    try:
        found = check_records(root, [f.resolve() for f in folders])
    except checker.CheckerError as error:
        print(error, file=sys.stderr)
        return error.code
    if found is None:
        print(checker.NOT_INSTALLED)
        return code
    count, problems = found
    print("\n".join(problems) if problems else f"ok: {count} records")
    return 1 if problems else code


def check_records(root: Path, folders: list[Path]) -> tuple[int, list[str]] | None:
    """The checker's records and problems of the plans folder, or of the named plan folders: a folder of this
    repository is checked with the repository (its .hal/records.toml applies), any other (an example folder laid
    out like a repository, `<tree>/plans/<plan>/`) with `--folder <tree>`. None without the checker."""
    real = root.resolve()
    if not folders:
        result = checker.check(repo=real)
        if result is None:
            return None
        return result["records"], [checker.line(p) for p in result["problems"] if p["path"].startswith(f"{PLANS}/")]
    count, problems, runs = 0, [], {}
    for path in folders:
        runs.setdefault(path.parent.parent, []).append(path.name)
    for tree, names in runs.items():
        result = checker.check(repo=real) if tree == real else checker.check(folder=tree)
        if result is None:
            return None
        count += result["records"]
        prefix = "" if tree == real else f"{os.path.relpath(tree, real)}/"
        problems += [checker.line(p, prefix) for p in result["problems"]
                     if any(p["path"].startswith(f"{PLANS}/{name}/") for name in names)]
    return count, problems


# What a subservant (a slot with plans/LEAD) may not do: plan.md is the lead's (hal2 shows the newest copy).
SUBSERVANT_REFUSES = ("new", "status", "assign", "grilled", "landing", "uat", "brief", "scaffold")
PARALLEL_COMMANDS = ("ready", "assign", "brief", "report", "reports", "watch")


def refuse_subservant(root: Path, command: str) -> None:
    marker = parallel.subservant_marker(root, Path.cwd())
    if marker and command in SUBSERVANT_REFUSES:
        raise PlanError(f"this slot is a subservant of slot {marker['slot']} (plan {marker['plan']} step "
                        f"{marker['step']}, plans/LEAD): it never edits plan.md; write your report with "
                        f"`plan.py report {marker['step']}` and tell the lead")


def parallel_steps(path: Path) -> list[dict]:
    steps = read_steps(path.read_text())
    if not steps or "needs" not in steps[0]:
        raise PlanError(f"{slug_of(path)} is no parallel plan: its step table has no Needs column")
    return steps


def run_parallel(root: Path, path: Path, args) -> int:
    """ready, assign, brief, report, reports, watch (skills plan 0013)."""
    slug, steps = slug_of(path), parallel_steps(path)
    if args.command == "ready":
        ready, waiting = parallel.schedule(steps, parallel.capacity(path.read_text()), args.limit)
        if not args.json:
            for s in ready:
                print(f"{s['number']}\t{s['step']}\t{', '.join(s['touches']) or '-'}")
            print("" if ready else "nothing ready", end="\n" if not ready else "")
            return 0
        result = {"plan": slug, "ready": ready, "waiting": waiting,
                  "running": [s for s in steps if parallel.kind(s["status"]) == "running"]}
    elif args.command == "assign":
        who = parallel.check_who(" ".join(args.who))
        step = next((s for s in steps if s["number"] == args.step), None)
        if step is None:
            raise PlanError(f"no step '{args.step}' in {slug}")
        ready, waiting = parallel.schedule(steps, parallel.capacity(path.read_text()))
        if step not in ready and not args.force:
            why = next((w["why"] for w in waiting if w["number"] == args.step), f"it is {step['status'] or 'open'}")
            raise PlanError(f"step {args.step} is not ready ({why}); --force assigns it anyway")
        slot = parallel.slot_of(who)
        if slot and not args.force and (why := parallel.slot_taken(root, slug, steps, args.step, slot)):
            raise PlanError(f"{why}; --force assigns it anyway")
        set_cells(path, args.step, {"who": who, "status": "running"})
        result = describe(root, path)
        worktree = parallel.slot_worktree(root, slot) if slot else None
        if worktree and worktree.resolve() != root.resolve():
            result["marker"] = str(parallel.write_marker(worktree, root.name, slug, args.step))
    elif args.command == "brief":
        step = next((s for s in steps if s["number"] == args.step), None)
        if step is None:
            raise PlanError(f"no step '{args.step}' in {slug}")
        brief = path.parent / "steps" / f"{args.step}.md"
        if not brief.exists():
            brief.parent.mkdir(exist_ok=True)
            brief.write_text(parallel.fill(
                "step-brief.md", number=args.step, slug=slug, plan_number=slug[:4], title=step["step"],
                lead=root.name, needs=", ".join(step["needs"]) or "none", touches=", ".join(step["touches"]) or "none",
                done_when=step["done_when"] or "<the check that proves the step>", who=step["who"] or "<who>"))
        result = {"plan": slug, "step": args.step, "brief": str(brief.relative_to(root)),
                  "prompt": parallel.brief_prompt(slug, args.step, root.name)}
    elif args.command == "report":
        marker = parallel.read_marker(root) or {}
        step = next((s for s in steps if s["number"] == args.step), None)
        if step is None:
            raise PlanError(f"no step '{args.step}' in {slug}")
        report = path.parent / "reports" / f"{args.step}.md"
        if not report.exists():
            report.parent.mkdir(exist_ok=True)
            report.write_text(parallel.fill(
                "report.md", number=args.step, slug=slug, title=step["step"], slot=root.name,
                lead=marker.get("slot", "<lead slot>"), date=dt.date.today().isoformat()))
        result = {"plan": slug, "step": args.step, "report": str(report.relative_to(root))}
    elif args.command == "reports":
        result = {"plan": slug, "arrived": parallel.arrived(root, slug, steps, fetch=not args.no_fetch)}
    else:
        return watch(root, path, args.interval, args.rounds)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


def watch(root: Path, path: Path, interval: float, rounds: int) -> int:
    """One line per report newly arrived on a subservant's branch, for the lead's background Monitor."""
    seen, n = set(), 0
    while True:
        for r in parallel.arrived(root, slug_of(path), read_steps(path.read_text())):
            if (r["number"], r["sha"]) not in seen:
                seen.add((r["number"], r["sha"]))
                print(f"report step {r['number']} from slot {r['slot']} at {r['sha']}: {r['report']}", flush=True)
        n += 1
        if rounds and n >= rounds:
            return 0
        time.sleep(interval)


def run_global(args) -> int:
    """The commands on the global plans folder: no git, no CURRENT_PLAN."""
    folder = (args.global_root or global_folder()).expanduser().resolve()
    root = use_global(folder)
    if args.command == "new":
        result = describe(root, new_global_plan(folder, args.title, args.goal, args.research))
    elif args.command == "list":
        result = [describe_safe(root, p) for p in plan_files(root)]
    elif args.command in ("status", "grilled"):
        if not args.plan:
            raise PlanError("a global plan has no current plan: name it with --plan <n>")
        path = resolve(root, args.plan)
        if args.command == "status":
            set_status(path, args.step, args.status)
        else:
            set_grilled(path, args.auto)
        result = describe(root, path)
    else:
        raise PlanError(f"'{args.command}' works on a repository only: global plans have no CURRENT_PLAN")
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
