"""The records of a plan folder (`plan.md`, `decisions.md`, `questions.md`, `handoff.md`) and their form: the
envelope's keys, each type's status values, heading and sections (rule 3 of hal2's decision record `record-formats`).

A tree of records is laid over a base repository: the files of an example folder that is laid out like a repository
resolve their links to real plans, records and code in the base. A file without `type` is legacy and has no problem.
"""

import os
import re
from dataclasses import dataclass, field
from pathlib import Path

import envelope

ENVELOPE = ["type", "schema", "title", "description", "status"]
LEDGER = {"status": ["open", "closed"], "keys": ["plan"], "optional": []}

# Per type: where the file lives, its legal status values, its own keys, its `# ` heading and its `## ` sections in
# order (`?`: may be missing, `*`: a pattern that may repeat at the end, None: sections are free or entries).
SPECS = {
    "Plan": {"path": r"plans/\d{4}-[^/]+/plan\.md", "status": ["open", "done", "abandoned"],
             "keys": ["id", "landing", "created"], "optional": ["parent", "grilled", "finished", "autogenerated"],
             "h1": r"Plan \d{4}: .+", "sections": ["Goal", "Context", "Steps", "Pre-authorized", "Notes?"]},
    "Decisions": {**LEDGER, "path": r"plans/\d{4}-[^/]+/decisions\.md", "h1": r"Decisions of plan \d{4}",
                  "sections": None},
    "Questions": {**LEDGER, "path": r"plans/\d{4}-[^/]+/questions\.md", "h1": r"Questions and answers",
                  "sections": None},
    "Handoff": {"path": r"plans/\d{4}-[^/]+/handoff\.md", "status": ["open", "closed"],
                "keys": ["plan", "updated", "branch", "at"], "optional": [], "h1": r"Handoff of plan \d{4}",
                "sections": ["Done?", "Next", "Watch out?", "Start with"]},
}


@dataclass
class Record:
    rel: str                      # the path below the tree's root, with forward slashes
    meta: dict | None             # None: no front matter
    body: str
    error: str = ""

    @property
    def type(self) -> str:
        return str((self.meta or {}).get("type") or "")


@dataclass
class Tree:
    root: Path
    base: Path
    cache: dict = field(default_factory=dict)

    def find(self, rel: str) -> Path | None:
        for top in (self.root, self.base):
            if (top / rel).exists():
                return top / rel
        return None

    def record(self, rel: str) -> Record | None:
        """The parsed record at `rel`; None when no such file exists."""
        if rel not in self.cache:
            path = self.find(rel)
            self.cache[rel] = load(path, rel) if path and path.is_file() else None
        return self.cache[rel]

    def matches(self, pattern: str) -> bool:
        return any(next(iter(top.glob(pattern)), None) for top in (self.root, self.base))

    def resolve(self, rel: str, target: str) -> str | None:
        """The tree path a relative link of the file `rel` points at; None when it leaves the tree."""
        path = os.path.normpath(os.path.join(os.path.dirname(rel), target)).replace(os.sep, "/")
        return None if path.startswith("..") else path

    def typed(self) -> list[Record]:
        """Every markdown file of the tree itself (never the base) that has a `type`."""
        out = []
        for path in sorted(self.root.rglob("*.md")):
            rec = self.record(path.relative_to(self.root).as_posix())
            if rec and (rec.type or rec.error):
                out.append(rec)
        return out


def load(path: Path, rel: str) -> Record:
    text = path.read_text()
    try:
        front, body = envelope.split(text)
        return Record(rel, envelope.parse(front) if front is not None else None, body)
    except envelope.FormatError as e:
        return Record(rel, {}, text, error=str(e))


def check_keys(rec: Record, spec: dict) -> list[str]:
    meta, problems = rec.meta, []
    required = ENVELOPE + spec["keys"]
    problems += [f"missing key `{k}`" for k in required if k not in meta]
    problems += [f"unknown key `{k}`" for k in meta if k not in required + spec["optional"]]
    problems += [f"`{k}` is empty" for k in ENVELOPE + ["id", "plan", "date"] if k in meta and meta[k] in (None, "")]
    problems += [f"`{k}` is not a list" for k in spec.get("lists", []) if not isinstance(meta.get(k), list)]
    if meta.get("schema") != 1:
        problems.append(f"`schema: {meta.get('schema')}` is not 1")
    if meta.get("status") not in spec["status"]:
        problems.append(f"status `{meta.get('status')}` is not one of {', '.join(spec['status'])}")
    if len(str(meta.get("description") or "")) > 200:
        problems.append(f"`description` has {len(str(meta['description']))} characters, over 200")
    if "landing" in meta and meta["landing"] not in ("auto", "manual"):
        problems.append(f"`landing: {meta['landing']}` is not auto or manual")
    return problems


def check_sections(found: list[str], expected: list[str]) -> list[str]:
    """`found` holds the expected sections in their order, optional ones may be missing, nothing else."""
    problems, rest = [], list(found)
    for want in expected:
        if want.startswith("*"):
            problems += [f"section `## {s}` is not allowed here" for s in rest if not re.fullmatch(want[1:], s)]
            return problems
        name = want.rstrip("?")
        if rest and rest[0] == name:
            rest.pop(0)
        elif not want.endswith("?"):
            problems.append(f"section `## {name}` is missing or out of order")
    return problems + [f"section `## {s}` is not allowed here" for s in rest]


def check_body(rec: Record, spec: dict, tree: Tree) -> list[str]:
    problems = []
    h1 = envelope.headings(rec.body, 1)
    if len(h1) != 1 or not re.fullmatch(spec["h1"], h1[0]):
        problems.append(f"the body needs one `# ` heading of the form `{spec['h1']}`")
    if spec["sections"]:
        problems += check_sections(envelope.headings(rec.body, 2), spec["sections"])
    for target in envelope.links(rec.body):
        rel = tree.resolve(rec.rel, target)
        if not rel or not tree.find(rel):
            problems.append(f"dead link: {target}" + ("" if rel else " (it leaves the tree)"))
    return problems


def check(rec: Record, tree: Tree, by_type: dict) -> list[str]:
    """Every problem of one record; a legacy file (no `type`) has none."""
    if rec.error:
        return [rec.error]
    if not rec.type:
        return []
    spec = SPECS.get(rec.type)
    if not spec:
        return [f"unknown type `{rec.type}` (a plan folder holds {', '.join(SPECS)})"]
    problems = check_keys(rec, spec)
    if not re.fullmatch(spec["path"], rec.rel):
        problems.append(f"a `{rec.type}` does not live at this path (`{spec['path']}`)")
    if problems:
        return problems
    return check_body(rec, spec, tree) + by_type[rec.type](rec, tree)
