"""The plan folder in the record format: what `plan.py new` writes, and `plan.py check` (hal2 plan 0206 step 8),
which runs hal2's records checker (hal2 plan 0214 step 6): every template `new` writes passes it.

The checker is `$HAL2_CLI_RECORDS`, else `hal2-cli-records` on PATH; the tests that need it are skipped without it.
hal2 tests its rules (one seeded fault per rule); here only that plan.py runs it and prints its problems.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPT = HERE / "plan.py"
sys.path.insert(0, str(HERE))

import checker  # noqa: E402
import envelope  # noqa: E402
import folder  # noqa: E402

CHECKER = checker.binary()
needs_checker = unittest.skipUnless(CHECKER, f"{checker.NAME} is not installed and ${checker.ENV} is unset")

ENTRY = """
## D1 · 2026-10-08 · user · in-force

**D:** Nothing lands tonight.
**Words:** "i do the mtm next morning"
"""


class FolderTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name).resolve()
        subprocess.run(["git", "init", "-q", "-b", "main"], cwd=self.root, check=True)

    def tearDown(self):
        self.tmp.cleanup()

    def run_plan(self, *args, env: dict | None = None) -> subprocess.CompletedProcess:
        return subprocess.run([sys.executable, str(SCRIPT), "--root", str(self.root), *args],
                              capture_output=True, text=True, env=env)

    def new(self, *args) -> Path:
        result = self.run_plan("new", *args)
        self.assertEqual(result.returncode, 0, result.stderr)
        return self.root / json.loads(result.stdout)["path"]

    def check(self, *args) -> tuple[int, str]:
        """The exit code and the output, without the plan numbers' own line."""
        result = self.run_plan("check", *args)
        return result.returncode, (result.stdout + result.stderr).replace("ok: no plan number is used twice\n", "")

    def edit(self, path: Path, old: str, new: str) -> None:
        text = path.read_text()
        self.assertIn(old, text)
        path.write_text(text.replace(old, new, 1))

    @needs_checker
    def test_new_writes_the_four_records_and_they_are_valid(self):
        plan = self.new("Deploy the hub", "--goal", "The hub runs on hal9k. Then the nodes follow.")
        self.assertEqual(sorted(p.name for p in plan.parent.iterdir()),
                         ["decisions.md", "handoff.md", "plan.md", "questions.md"])
        meta = envelope.parse(envelope.split(plan.read_text())[0])
        self.assertEqual((meta["type"], meta["id"], meta["status"], meta["landing"]), ("Plan", 1, "open", "auto"))
        self.assertEqual(meta["description"], "The hub runs on hal9k.")
        self.assertEqual(self.check(), (0, "ok: 4 records\n"))

    @needs_checker
    def test_every_kind_of_new_plan_is_valid(self):
        self.new("Compare queues", "--research")
        self.new("Many hands", "--parallel")
        self.new("Watcher fix", "--autogenerated", "sanity-watch")
        self.new('A "quoted" title: with [brackets] # and a hash', "--manual-landing")
        self.run_plan("grilled", "--auto")
        self.assertEqual(self.check(), (0, "ok: 16 records\n"))

    @needs_checker
    def test_a_long_goal_is_cut_to_a_description_of_200_characters(self):
        plan = self.new("Long", "--goal", "word " * 80)
        self.assertLessEqual(len(envelope.get(plan.read_text(), "description")), 200)
        self.assertEqual(self.check()[0], 0)

    @needs_checker
    def test_a_legacy_plan_passes_and_gets_no_scaffold(self):
        legacy = self.root / "plans" / "0001-old" / "plan.md"
        legacy.parent.mkdir(parents=True)
        legacy.write_text("# Plan 0001: old\n\n## Anything\n\n| # | Step | Status |\n|---|---|---|\n| 1 | x | next |\n")
        self.assertEqual(self.check(), (0, "ok: 0 records\n"))
        self.assertEqual(self.run_plan("scaffold", "--plan", "1").returncode, 0)
        self.assertEqual([p.name for p in legacy.parent.iterdir()], ["plan.md"])

    @needs_checker
    def test_the_last_step_done_closes_the_ledgers_and_the_handoff(self):
        plan = self.new("Tiny")
        for step in ("1", "2"):
            self.run_plan("status", step, "done")
        for name in folder.SIBLINGS:
            self.assertEqual(envelope.get((plan.parent / name).read_text(), "status"), "closed", name)
        self.assertEqual(self.check(), (0, "ok: 4 records\n"))
        self.run_plan("status", "2", "next")
        self.assertEqual(envelope.get((plan.parent / "handoff.md").read_text(), "status"), "open")
        self.assertEqual(self.check()[0], 0)

    def test_a_step_between_first_and_last_leaves_the_handoff_untouched(self):
        """hal2's autoclear counts a handoff.md written since its request as the hand-off."""
        import os
        plan = self.new("Tiny")
        handoff = plan.parent / "handoff.md"
        os.utime(handoff, (1_000_000_000, 1_000_000_000))
        self.run_plan("status", "1", "done")
        self.run_plan("status", "2", "next")
        self.assertEqual(handoff.stat().st_mtime, 1_000_000_000)

    @needs_checker
    def test_scaffold_writes_a_missing_ledger_and_keeps_the_others(self):
        plan = self.new("Tiny")
        (plan.parent / "decisions.md").write_text((plan.parent / "decisions.md").read_text() + ENTRY)
        (plan.parent / "questions.md").unlink()
        code, out = self.check()
        self.assertEqual(code, 1)
        self.assertIn("questions.md is missing or without front matter", out)
        self.assertEqual(self.run_plan("scaffold").returncode, 0)
        self.assertIn("i do the mtm next morning", (plan.parent / "decisions.md").read_text())
        self.assertEqual(self.check(), (0, "ok: 4 records\n"))

    def seeded(self, name: str, old: str, new: str, expect: str) -> None:
        plan = self.new("Tiny")
        self.edit(plan.parent / name, old, new)
        code, out = self.check()
        self.assertEqual(code, 1, out)
        self.assertIn(expect, out)
        self.assertIn(f"plans/0001-tiny/{name}: ", out)

    @needs_checker
    def test_a_problem_is_printed_with_its_path_and_rule(self):
        self.seeded("plan.md", "landing: auto\n", "landing: auto\nowner: me\n", "unknown key `owner` (spec:unknown-key)")

    @needs_checker
    def test_a_problem_outside_the_plans_folder_is_not_the_plan_check_s(self):
        self.new("Tiny")
        (self.root / "research" / "0001-x").mkdir(parents=True)
        (self.root / "research" / "0001-x" / "research.md").write_text("---\ntype: Research\nschema: 1\n---\n# x\n")
        self.assertEqual(self.check(), (0, "ok: 5 records\n"))

    def test_without_the_checker_the_records_are_unchecked_and_pass(self):
        """The advisory path: no binary, one line, exit 0 (also with a broken plan)."""
        plan = self.new("Tiny")
        self.edit(plan, "landing: auto\n", "landing: auto\nowner: me\n")
        env = {**os.environ, checker.ENV: str(self.root / "no-such-binary")}
        result = self.run_plan("check", env=env)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout, "ok: no plan number is used twice\n" + checker.NOT_INSTALLED + "\n")
        env = {k: v for k, v in os.environ.items() if k != checker.ENV}
        env["PATH"] = "/usr/bin:/bin"  # git, never hal2-cli-records
        result = self.run_plan("check", str(plan.parent), env=env)
        self.assertEqual((result.returncode, result.stdout), (0, checker.NOT_INSTALLED + "\n"))

    @needs_checker
    def test_a_named_folder_is_checked_alone_and_resolves_its_links_in_the_repository_around_it(self):
        """An example plan folder laid out like a repository (hal2 plan 0202's examples/plans/<plan>/) links real
        files of the repository that holds it."""
        (self.root / "docs").mkdir()
        (self.root / "docs" / "guide.md").write_text("# Guide\n")
        plan = self.new("Tiny")
        self.edit(plan, "- <links to the intent doc", "- [the guide](../../docs/guide.md)\n- <links to the intent doc")
        examples = self.root / "plans" / "0001-tiny" / "examples" / "plans"
        examples.mkdir(parents=True)
        copy = examples / "0001-tiny"
        shutil.copytree(plan.parent, copy, ignore=shutil.ignore_patterns("examples"))
        self.assertEqual(self.check(str(copy)), (0, "ok: 4 records\n"))
        self.edit(copy / "plan.md", "status: open", "status: abandoned")
        code, out = self.check(str(copy))
        self.assertEqual(code, 1)
        self.assertIn("plans/0001-tiny/examples/plans/0001-tiny/", out)
        self.assertIn("abandoned", out)
        self.assertEqual(self.run_plan("check", str(self.root / "docs")).returncode, 1)


if __name__ == "__main__":
    unittest.main()
