"""The plan folder in the record format: what `plan.py new` writes, and `plan.py check` (hal2 plan 0206 step 8)."""
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPT = HERE / "plan.py"
sys.path.insert(0, str(HERE))

import envelope  # noqa: E402
import folder  # noqa: E402

ENTRY = """
## D1 · 2026-10-08 · user · in-force

**D:** Nothing lands tonight.
**Words:** "i do the mtm next morning"
"""


class FolderTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name).resolve()
        subprocess.run(["git", "init", "-q", "-b", "main"], cwd=self.root, check=True)

    def tearDown(self):
        self.tmp.cleanup()

    def run_plan(self, *args) -> subprocess.CompletedProcess:
        return subprocess.run([sys.executable, str(SCRIPT), "--root", str(self.root), *args],
                              capture_output=True, text=True)

    def new(self, *args) -> Path:
        result = self.run_plan("new", *args)
        self.assertEqual(result.returncode, 0, result.stderr)
        return self.root / json.loads(result.stdout)["path"]

    def check(self, *args) -> tuple[int, str]:
        """The exit code and the output, without the plan numbers' own line."""
        result = self.run_plan("check", *args)
        return result.returncode, (result.stdout + result.stderr).replace("ok: no plan number is used twice\n", "")

    def edit(self, path: Path, old: str, new: str) -> None:
        text = path.read_text()
        self.assertIn(old, text)
        path.write_text(text.replace(old, new, 1))

    def test_new_writes_the_four_records_and_they_are_valid(self):
        plan = self.new("Deploy the hub", "--goal", "The hub runs on hal9k. Then the nodes follow.")
        self.assertEqual(sorted(p.name for p in plan.parent.iterdir()),
                         ["decisions.md", "handoff.md", "plan.md", "questions.md"])
        meta = envelope.parse(envelope.split(plan.read_text())[0])
        self.assertEqual((meta["type"], meta["id"], meta["status"], meta["landing"]), ("Plan", 1, "open", "auto"))
        self.assertEqual(meta["description"], "The hub runs on hal9k.")
        self.assertEqual(self.check(), (0, "ok: 4 records\n"))

    def test_every_kind_of_new_plan_is_valid(self):
        self.new("Compare queues", "--research")
        self.new("Many hands", "--parallel")
        self.new("Watcher fix", "--autogenerated", "sanity-watch")
        self.new('A "quoted" title: with [brackets] # and a hash', "--manual-landing")
        self.run_plan("grilled", "--auto")
        self.assertEqual(self.check(), (0, "ok: 16 records\n"))

    def test_a_long_goal_is_cut_to_a_description_of_200_characters(self):
        plan = self.new("Long", "--goal", "word " * 80)
        self.assertLessEqual(len(envelope.get(plan.read_text(), "description")), 200)
        self.assertEqual(self.check()[0], 0)

    def test_a_legacy_plan_passes_and_gets_no_scaffold(self):
        legacy = self.root / "plans" / "0001-old" / "plan.md"
        legacy.parent.mkdir(parents=True)
        legacy.write_text("# Plan 0001: old\n\n## Anything\n\n| # | Step | Status |\n|---|---|---|\n| 1 | x | next |\n")
        self.assertEqual(self.check(), (0, "ok: 0 records\n"))
        self.assertEqual(self.run_plan("scaffold", "--plan", "1").returncode, 0)
        self.assertEqual([p.name for p in legacy.parent.iterdir()], ["plan.md"])

    def test_the_last_step_done_closes_the_ledgers_and_the_handoff(self):
        plan = self.new("Tiny")
        for step in ("1", "2"):
            self.run_plan("status", step, "done")
        for name in folder.SIBLINGS:
            self.assertEqual(envelope.get((plan.parent / name).read_text(), "status"), "closed", name)
        self.assertEqual(self.check(), (0, "ok: 4 records\n"))
        self.run_plan("status", "2", "next")
        self.assertEqual(envelope.get((plan.parent / "handoff.md").read_text(), "status"), "open")
        self.assertEqual(self.check()[0], 0)

    def test_a_step_between_first_and_last_leaves_the_handoff_untouched(self):
        """hal2's autoclear counts a handoff.md written since its request as the hand-off."""
        import os
        plan = self.new("Tiny")
        handoff = plan.parent / "handoff.md"
        os.utime(handoff, (1_000_000_000, 1_000_000_000))
        self.run_plan("status", "1", "done")
        self.run_plan("status", "2", "next")
        self.assertEqual(handoff.stat().st_mtime, 1_000_000_000)

    def test_scaffold_writes_a_missing_ledger_and_keeps_the_others(self):
        plan = self.new("Tiny")
        (plan.parent / "decisions.md").write_text((plan.parent / "decisions.md").read_text() + ENTRY)
        (plan.parent / "questions.md").unlink()
        code, out = self.check()
        self.assertEqual(code, 1)
        self.assertIn("questions.md: missing or without front matter", out)
        self.assertEqual(self.run_plan("scaffold").returncode, 0)
        self.assertIn("i do the mtm next morning", (plan.parent / "decisions.md").read_text())
        self.assertEqual(self.check(), (0, "ok: 4 records\n"))

    def seeded(self, name: str, old: str, new: str, expect: str) -> None:
        plan = self.new("Tiny")
        self.edit(plan.parent / name, old, new)
        code, out = self.check()
        self.assertEqual(code, 1, out)
        self.assertIn(expect, out)
        self.assertIn(f"plans/0001-tiny/{name}: ", out)

    def test_an_unknown_key_fails(self):
        self.seeded("plan.md", "landing: auto\n", "landing: auto\nowner: me\n", "unknown key `owner`")

    def test_a_decisions_section_in_the_plan_fails(self):
        self.seeded("plan.md", "## Notes", "## Decisions\n\n- one\n\n## Notes", "section `## Decisions` is not allowed")

    def test_a_status_that_does_not_fit_the_step_table_fails(self):
        self.seeded("plan.md", "status: open", "status: done", "does not fit the step table")

    def test_a_user_decision_without_its_words_fails(self):
        self.seeded("decisions.md", "-->\n", "-->\n" + ENTRY.replace('**Words:** "i do the mtm next morning"\n', ""),
                    "D1: decided by `user`, but no **Words:** line")

    def test_an_answered_question_without_its_answer_fails(self):
        self.seeded("questions.md", "-->\n", "-->\n\n## Q1 · 2026-10-08 · agent · answered 2026-10-08\n\n**Q:** Which?\n",
                    "Q1: `answered` does not fit its **A:** line")

    def test_a_handoff_with_a_machine_local_fact_fails(self):
        self.seeded("handoff.md", "## Start with", "## Watch out\n\n- The build runs in pane %54.\n\n## Start with",
                    "machine-local fact (a pane id)")

    def test_a_dead_link_fails(self):
        self.seeded("plan.md", "[handoff.md](handoff.md)", "[handoff.md](hand-off.md)", "dead link: hand-off.md")

    def test_a_named_folder_is_checked_alone_and_resolves_its_links_in_the_repository_around_it(self):
        """An example plan folder laid out like a repository (hal2 plan 0202's examples/plans/<plan>/) links real
        files of the repository that holds it."""
        (self.root / "docs").mkdir()
        (self.root / "docs" / "guide.md").write_text("# Guide\n")
        plan = self.new("Tiny")
        self.edit(plan, "- <links to the intent doc", "- [the guide](../../docs/guide.md)\n- <links to the intent doc")
        examples = self.root / "plans" / "0001-tiny" / "examples" / "plans"
        examples.mkdir(parents=True)
        copy = examples / "0001-tiny"
        shutil.copytree(plan.parent, copy, ignore=shutil.ignore_patterns("examples"))
        self.assertEqual(self.check(str(copy)), (0, "ok: 4 records\n"))
        self.edit(copy / "plan.md", "status: open", "status: abandoned")
        code, out = self.check(str(copy))
        self.assertEqual(code, 1)
        self.assertIn("status `open` but the plan is `abandoned`", out)
        self.assertEqual(self.run_plan("check", str(self.root / "docs")).returncode, 1)


if __name__ == "__main__":
    unittest.main()
