#!/usr/bin/env bash
# Generated by `hal plan spec render-verify`.
# Edit spec.md Success Criteria; re-render. Do not edit by hand.
set -uo pipefail
fails=0
total=0

crit_001() {
  # unit tests pass
  cd skills/dm-summarize-video/scripts && python3 -m unittest discover -p 'test_*.py'
}

crit_002() {
  # plugin manifests and skill rules consistent (incl. prerequisite scripts)
  python3 scripts/check-plugins.py
}

crit_003() {
  # prerequisite check passes on this machine
  skills/dm-summarize-video/scripts/check-prerequisites.sh
}

crit_004() {
  # Claude plugin still validates
  claude plugin validate . --strict
}

crit_005() {
  # CLAUDE.md and AGENTS.md document the script rules
  grep -q 'check-prerequisites' CLAUDE.md && grep -q 'check-prerequisites' AGENTS.md
}

main() {
  total=$((total + 1))
  out=$(crit_001 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'unit tests pass'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'unit tests pass'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_002 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'plugin manifests and skill rules consistent (incl. prerequisite scripts)'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'plugin manifests and skill rules consistent (incl. prerequisite scripts)'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_003 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'prerequisite check passes on this machine'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'prerequisite check passes on this machine'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_004 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'Claude plugin still validates'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'Claude plugin still validates'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_005 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'CLAUDE.md and AGENTS.md document the script rules'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'CLAUDE.md and AGENTS.md document the script rules'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  echo "---"
  echo "$((total - fails))/$total criteria PASSED"
  if [[ "$fails" -gt 0 ]]; then exit 3; fi
  exit 0
}

main "$@"
