#!/usr/bin/env bash
# Generated by `hal plan spec render-verify`.
# Edit spec.md Success Criteria; re-render. Do not edit by hand.
set -uo pipefail
fails=0
total=0

crit_001() {
  # all tell-me tests pass (existing + new)
  skills/tell-me/scripts/run-tests.sh
}

crit_002() {
  # plugin manifests + per-source prereq scripts are consistent
  python3 scripts/check-plugins.py && python3 -m unittest discover -s scripts
}

crit_003() {
  # router classifies every source
  cd skills/tell-me/scripts && for u in https://youtu.be/dQw4w9WgXcQ https://github.com/yt-dlp/yt-dlp https://x.com/jack/status/20 https://news.ycombinator.com/item?id=1 https://example.com/blog/post ../SKILL.md; do python3 shared/route.py "$u" || exit 1; done
}

crit_004() {
  # every source has a subskill, a template and is linked from SKILL.md
  cd skills/tell-me && for s in video web github x hn file; do test -f subskills/$s/SUBSKILL.md && test -f templates/$s/template.md && grep -q "subskills/$s/SUBSKILL.md" SKILL.md || exit 1; done
}

crit_005() {
  # no transcript.md left in new-layout scripts (content.md everywhere)
  ! grep -rn 'transcript.md' skills/tell-me/scripts --include='*.py' | grep -v migrate_library | grep -v test_
}

crit_006() {
  # no nested skill files
  test -z "$(find skills/tell-me -mindepth 2 -iname skill.md)"
}

crit_007() {
  # SKILL.md stays under 500 lines
  test "$(wc -l < skills/tell-me/SKILL.md)" -lt 500
}

main() {
  total=$((total + 1))
  out=$(crit_001 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'all tell-me tests pass (existing + new)'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'all tell-me tests pass (existing + new)'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_002 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'plugin manifests + per-source prereq scripts are consistent'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'plugin manifests + per-source prereq scripts are consistent'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_003 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'router classifies every source'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'router classifies every source'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_004 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'every source has a subskill, a template and is linked from SKILL.md'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'every source has a subskill, a template and is linked from SKILL.md'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_005 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'no transcript.md left in new-layout scripts (content.md everywhere)'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'no transcript.md left in new-layout scripts (content.md everywhere)'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_006 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'no nested skill files'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'no nested skill files'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_007 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'SKILL.md stays under 500 lines'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'SKILL.md stays under 500 lines'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  echo "---"
  echo "$((total - fails))/$total criteria PASSED"
  if [[ "$fails" -gt 0 ]]; then exit 3; fi
  exit 0
}

main "$@"
