#!/usr/bin/env python3
"""Generate the shortcut skills listed in aliases.json.

  python3 scripts/gen-aliases.py [--check]

aliases.json maps a shortcut to a skill and the arguments it puts in front of the user's own:
{"c": {"skill": "handoff", "args": "continue"}} makes `/c` run `/handoff continue`. Each shortcut becomes
skills/<shortcut>/SKILL.md, a stub that hands over to the target skill; it is model-invocation disabled, so only the
user's typed `/<shortcut>` runs it. Stubs of shortcuts removed from aliases.json are deleted, and
.claude-plugin/plugin.json lists exactly the skills on disk. --check changes nothing and exits 1 when anything is
out of date (check-plugins.py runs it).
"""
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARKER = "<!-- generated by scripts/gen-aliases.py from aliases.json; edit those, not this file -->"


def load_aliases(root: Path = ROOT) -> dict[str, dict]:
    path = root / "aliases.json"
    return json.loads(path.read_text()) if path.is_file() else {}


def stub(alias: str, skill: str, args: str) -> str:
    call = f"/{skill} {args}".strip()
    return (
        f"---\nname: {alias}\n"
        f"description: Shortcut for `{call}` — `/{alias} <args>` runs `{call} <args>` of the {skill} skill.\n"
        f"disable-model-invocation: true\n---\n\n{MARKER}\n\n"
        f"# /{alias}\n\n"
        f"Shortcut for `{call}`. Read [`../{skill}/SKILL.md`](../{skill}/SKILL.md) and carry out `{call}`, with any "
        f"arguments given to `/{alias}` appended, exactly as that skill describes it.\n"
    )


def wanted_files(root: Path = ROOT) -> dict[Path, str]:
    """SKILL.md path -> content for every alias; raises ValueError on a bad entry."""
    files = {}
    for alias, entry in load_aliases(root).items():
        skill = entry.get("skill", "")
        target = root / "skills" / skill / "SKILL.md"
        if not target.is_file() or MARKER in target.read_text():
            raise ValueError(f"alias '{alias}': '{skill}' is not a skill of this repo")
        own = root / "skills" / alias / "SKILL.md"
        if own.is_file() and MARKER not in own.read_text():
            raise ValueError(f"alias '{alias}' clashes with the skill skills/{alias}")
        files[own] = stub(alias, skill, entry.get("args", ""))
    return files


def stale_stubs(root: Path, wanted: dict[Path, str]) -> list[Path]:
    return [p for p in sorted((root / "skills").glob("*/SKILL.md")) if MARKER in p.read_text() and p not in wanted]


def plugin_skills(root: Path, wanted: dict[Path, str], stale: list[Path]) -> list[str]:
    on_disk = {p.parent.name for p in (root / "skills").glob("*/SKILL.md")}
    on_disk |= {p.parent.name for p in wanted}
    on_disk -= {p.parent.name for p in stale}
    return [f"./skills/{name}" for name in sorted(on_disk)]


def main(argv: list[str], root: Path = ROOT) -> int:
    check = "--check" in argv
    try:
        wanted = wanted_files(root)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    stale = stale_stubs(root, wanted)
    manifest_path = root / ".claude-plugin" / "plugin.json"
    manifest = json.loads(manifest_path.read_text())
    skills = plugin_skills(root, wanted, stale)

    changes = [p for p, text in wanted.items() if not p.is_file() or p.read_text() != text]
    out_of_date = changes or stale or manifest.get("skills") != skills
    if check:
        for p in changes:
            print(f"error: {p.relative_to(root)} is out of date (run scripts/gen-aliases.py)", file=sys.stderr)
        for p in stale:
            print(f"error: {p.relative_to(root)} has no entry in aliases.json (run scripts/gen-aliases.py)",
                  file=sys.stderr)
        return 1 if out_of_date else 0

    for p in changes:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(wanted[p])
        print(f"write  {p.relative_to(root)}")
    for p in stale:
        shutil.rmtree(p.parent)
        print(f"remove {p.parent.relative_to(root)}")
    if manifest.get("skills") != skills:
        listing = "".join(f'\n    "{s}",' for s in skills).rstrip(",")
        # rewrite only the skills array, so the rest of the manifest keeps its formatting
        text = re.sub(r'"skills": \[[^\]]*\]', lambda _: f'"skills": [{listing}\n  ]', manifest_path.read_text())
        manifest_path.write_text(text)
        print(f"write  {manifest_path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
